# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-08 08:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companyapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobopenings',
            old_name='role_name',
            new_name='EmployeeRole',
        ),
    ]
